version: '3.9'

services:
  # üß± Database
  mysql:
    image: mysql:8.0
    container_name: booking-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: evrental
      MYSQL_USER: evuser
      MYSQL_PASSWORD: evpass
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - ev-rental-network

  # üñ•Ô∏è Adminer (UI ƒë·ªÉ xem database)
  adminer:
    image: adminer
    container_name: ev-adminer
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - ev-rental-network

  # üß© Admin Service
  admin-svc:
    build: ./services/admin-svc
    container_name: admin-svc
    environment:
      PORT: 3001
    ports:
      - "3001:3001"
    networks:
      - ev-rental-network
  # üöó Rental Service
  rental-svc:
    build: ./services/rental-svc
    container_name: rental-svc
    environment:
      RABBITMQ_URL: amqp://rabbitmq:5672
      PORT: 3002
      DATABASE_URL: mysql://evuser:evpass@booking-mysql:3306/evrental?authPlugins=mysql_native_password&connection_limit=10&pool_timeout=20
      SHADOW_DATABASE_URL: mysql://root:root@booking-mysql:3306/evrental_shadow?authPlugins=mysql_native_password
      CORS_ORIGIN: "*"
    depends_on:
      mysql:
        condition: service_healthy
      admin-svc:
        condition: service_started
    ports:
      - "3002:3002"
    networks:
      - ev-rental-network
  # üöô Fleet Service (n∆°i upload ·∫£nh l√™n AWS S3)
  fleet-svc:
    build: ./services/fleet-svc
    container_name: fleet-svc
    env_file:
      - ./services/fleet-svc/.env # ‚öôÔ∏è load key AWS t·ª´ ƒë√¢y
    environment:
      PORT: 3003
      DATABASE_URL: mysql://evuser:evpass@booking-mysql:3306/evrental?authPlugins=mysql_native_password&connection_limit=10&pool_timeout=20
      SHADOW_DATABASE_URL: mysql://root:root@booking-mysql:3306/evrental_shadow?authPlugins=mysql_native_password
    depends_on:
      mysql:
        condition: service_healthy
      admin-svc:
        condition: service_started
    ports:
      - "3003:3003"
    networks:
      - ev-rental-network
  # üåê Frontend (React/Vite)
  frontend:
    build: ./frontend
    container_name: ev-frontend
    ports:
      - "3004:3000"
    depends_on:
      - admin-svc
      - rental-svc
      - fleet-svc
    environment:
      - NODE_ENV=production
    networks:
      - ev-rental-network

volumes:
  dbdata:


networks:
  ev-rental-network:
    # ‚Üê Th√™m shared network
    external: true
    name: ev-rental-network
